"""
    Thin wrapper around cantonese_rs.
    The Cantonese interpreter CLI and REPL.
"""

import cmd
import os
import sys
import argparse
import traceback
import textwrap

sys.path.append(os.getcwd())
sys.dont_write_bytecode = True

try:
    from . import import_hook  # noqa: F401
    from ._core import (
        CantoneseCompileError,
        compile_with_diagnostics,
        to_python,
        to_python_with_line_map,
        tokenize,
    )
    from .libs import bootstrap, lib_env
    from .error_mapper import run_with_mapping

    bootstrap()
except ImportError as exc:
    raise ImportError(
        "Failed to initialize Cantonese runtime. "
        "Build and install the Rust extension with `maturin develop` "
        "(or `pip install .`)."
    ) from exc

_version_ = "Cantonese\033[5;33m 1.0.12\033[0m Copyright (C) 2020-2026\033[5;35m StepfenShawn\033[0m"
logo = (
    "\033[0;34m"
    + r"""
   ______            __                           
  / ________ _____  / /_____  ____  ___  ________ 
 / /   / __ `/ __ \/ __/ __ \/ __ \/ _ \/ ___/ _ \
/ /___/ /_/ / / / / /_/ /_/ / / / /  __(__  /  __/
\____/\__,_/_/ /_/\__/\____/_/ /_/\___/____/\___/ 
         
"""
    + "\033[0m"
    + "Keep cantonese alive!\nSource: https://github.com/StepfenShawn/Cantonese\n鐘意嘅話star埋我啊! Thank you!"
)

class Options:
    dump_lex = False
    mkfile = False
    debug = False

args = None


def create_cli():
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("file", nargs="?", default="")
    arg_parser.add_argument("others", nargs="?", default="")
    arg_parser.add_argument(
        "-to_py", action="store_true", help="Translate Cantonese to Python"
    )
    arg_parser.add_argument(
        "-讲翻py", action="store_true", help="Translate Cantonese to Python"
    )
    arg_parser.add_argument("-allow_pyc", action="store_true")
    arg_parser.add_argument("-build", action="store_true")
    arg_parser.add_argument("-z", action="store_true")
    arg_parser.add_argument("-lex", action="store_true")
    arg_parser.add_argument("-debug", action="store_true")
    arg_parser.add_argument(
        "-v", "--version", action="store_true", help="Print the version"
    )
    arg_parser.add_argument("-mkfile", action="store_true")

    return arg_parser.parse_args()


def start_cantonese(run_fn, exit_on_error=True):
    """Run a compilation/execution function and format errors."""
    try:
        return run_fn()
    except CantoneseCompileError as e:
        print("!!編譯期間瀨嘢:(\n")
        print(e)
        if exit_on_error:
            sys.exit(1)
        raise
    except Exception as e:
        show_full_tb = args is not None and getattr(args, "z", False)
        if show_full_tb:
            traceback.print_exc()
        else:
            tb = traceback.extract_tb(e.__traceback__)
            if tb:
                filename, lineno, funcname, line = tb[-1]
                print(
                    f"!!編譯器內部瀨嘢:(\n\n -> `{funcname}`函數\n"
                    f" -> 喺編譯器源代碼 '{filename}' 嘅{lineno}行:\n"
                    f" ->   {line}\n 發生 {e}\n\n 用 `-z` 查看完整錯誤信息."
                )
            else:
                print(f"!!瀨嘢:(\n發生 {e}\n\n 用 `-z` 查看完整錯誤信息.")
        if exit_on_error:
            sys.exit(1)
        raise


def _show_pretty_lex(tokens):
    for token in tokens:
        print(token)


def cantonese_run(
    code: str, is_to_py: bool, file: str, REPL=False, get_py_code=False
) -> None:
    """Compile and optionally execute a Cantonese source file."""
    os.environ["CUR_FILE"] = file

    if Options.dump_lex:
        tokens = tokenize(code, file)
        _show_pretty_lex(tokens)
        return

    py_code, diagnostics = compile_with_diagnostics(code, file)
    if diagnostics:
        for d in diagnostics:
            print(d.render(code, colors=True))
        raise CantoneseCompileError(diagnostics[0].message)
    _, line_map = to_python_with_line_map(code, file)

    if is_to_py:
        print("-> To python:")
        out_format = textwrap.indent(py_code, "  ")
        print(out_format)
        print("->")

    if Options.mkfile:
        if file.endswith(".cantonese"):
            py_file = file[: -len(".cantonese")] + ".py"
        else:
            py_file = file + ".py"
        with open(py_file, "w", encoding="utf-8") as f:
            f.write("###########################################\n")
            f.write("#        Generated by Cantonese           #\n")
            f.write("###########################################\n")
            f.write("# Run it by 'cantonese " + py_file + " -build' \n")
            f.write(py_code)

    if Options.debug:
        import dis

        print(dis.dis(py_code))
        return

    if get_py_code:
        return py_code

    show_full_tb = args is not None and getattr(args, "z", False)
    if show_full_tb:
        code_obj = compile(py_code, file, "exec")
        exec(code_obj, lib_env)
    else:
        try:
            run_with_mapping(py_code, line_map, code, file, lib_env)
        except Exception:
            # Diagnostic already printed to stderr by run_with_mapping.
            if REPL:
                raise
            sys.exit(1)


class 交互(cmd.Cmd):
    def __init__(self):
        super().__init__()
        self.prompt = "> "

    def run(self, code):
        if code in lib_env:
            print(lib_env[code])
        try:
            exec(code, lib_env)
        except Exception as e:
            print(f"\033[0;31m濑嘢!!!\033[0m: {e}")

    def default(self, code):
        os.environ["REPL_CONTEXT"] = code
        if code is None:
            return
        if code == ".quit":
            sys.exit(0)
        try:
            py_code = start_cantonese(
                lambda: cantonese_run(
                    code, False, "【標準輸入】", REPL=True, get_py_code=True
                ),
                exit_on_error=False,
            )
        except Exception:
            return
        self.run(py_code)


def 开始交互():
    import time

    print(_version_)
    交互().cmdloop(
        "本地時間: " + str(time.asctime(time.localtime(time.time()))) + ", 天氣唔知點"
    )


def main():
    global args

    args = create_cli()

    if args.version:
        print(_version_, logo)
        sys.exit(0)

    if not args.file:
        sys.exit(开始交互())

    if not os.path.exists(args.file):
        print("Error occurred when checking the path of file!")
        print(f" File {args.file}")
        try:
            print("      " + "^" * len(args.file.encode("gbk")))
        except Exception:
            print("      " + "^" * len(args.file))
        print("\033[0;31m濑嘢!!!\033[0m: 揾唔到你嘅文件 :(")
        sys.exit(1)

    file_dir = os.path.dirname(os.path.abspath(args.file))
    sys.path.insert(0, file_dir if file_dir else "./")

    if args.allow_pyc:
        sys.dont_write_bytecode = False

    Options.dump_lex = args.lex
    Options.debug = args.debug
    Options.mkfile = args.mkfile

    is_to_py = args.to_py or args.讲翻py

    with open(args.file, encoding="utf-8") as f:
        code = f.read()

    if args.build:
        if args.file.endswith(".cantonese"):
            py_code, diagnostics = compile_with_diagnostics(code, args.file)
            if diagnostics:
                for d in diagnostics:
                    print(d.render(code, colors=True))
                sys.exit(1)
            code = py_code
        code_obj = compile(code, args.file, "exec")
        exec(code_obj, lib_env)
        sys.exit(0)

    start_cantonese(lambda: cantonese_run(code, is_to_py, args.file))


if __name__ == "__main__":
    # Support colorful fonts on windows
    if os.name == "nt":
        os.system("")

    main()
